### ISSUE TITLE
Express Routes

### ISSUE THREAD

**Issue by unctarheel87** [unctarheel87/Team-1#16]
- [ ] set up get routes for html pages
- [ ] set up post routes and test postman

**Comment by jenguin777** [comment]
Are you working in routes.js for this issue? I did a pull request and I see this in apiRoutes.js:

app.get("/", function(req, res) {
    db.User.find({}).then(response => {
      console.log(response);
    })
    res.send('index.html');
  });

Let's talk about what is going in routes.js and apiRoutes.js. I think we may step on each other. I just checked in (pull request is awaiting approval) put and post in apiRoutes.js.

**Comment by unctarheel87** [comment]
Jen, this was just basic code to make sure our heroku build was working.  so you are free to delete this route with your own.  I checked your pull request; you have some travis errors :)

**Comment by unctarheel87** [comment]
also server.js points to apiRoutes.js.  So we can avoid routes.js. one of us can delete it on a push

**Comment by jenguin777** [comment]
Deleted route
