### ISSUE TITLE
Update apiRoutes.js

### ISSUE THREAD

**Issue by jenguin777** [unctarheel87/Team-1#23]
- [x] Add get to serve up html ("/")
- [x] Add get (findAll) for User with include() for Message and Interest so that all come back as 1 object
- [x] Add post (create) for User
- [x] Add post (create) for Message 
- [x] Add post (create) for Interest
Add put (update) for User (condition ???id???) --> future enhancement
- [x] Add put (update) for Message (condition ???id???)
- [x] Add put (update) for Interest (condition ???id???)
Add post (destroy) for User (condition ???id???)  --> future enhancement
- [x] Add post (destroy) for Message (condition ???id???) 
- [x] Add post (destroy) for Interest (condition ???id???)

**Comment by jenguin777** [comment]
Hi Team,

Please let me know if we need any of these:
Add put (update) for User (condition ???id???) --> future enhancement
  Add put (update) for Message (condition ???id???)
  Add put (update) for Interest (condition ???id???)
  Add post (destroy) for User (condition ???id???) --> future enhancement
  Add post (destroy) for Message (condition ???id???) --> future enhancement
  Add post (destroy) for Interest (condition ???id???) --> future enhancement

**Comment by unctarheel87** [comment]
just closed down some finished issues.  

we will need update and destroy routes for the Messages and Interests.  updates and destroys for the User we can leave for future updates.

**Comment by jenguin777** [comment]
ok, updated issue accordingly. Will work on those tonight.

**Comment by jenguin777** [comment]
Finished deletes, travis passed
